# Customer ID=8327; Build=0x3b95c; Copyright (c) 2007-2009 by Tensilica Inc.  ALL RIGHTS RESERVED.
# These coded instructions, statements, and computer programs are the
# copyrighted works and confidential proprietary information of Tensilica Inc.
# They may not be modified, copied, reproduced, distributed, or disclosed to
# third parties in any manner, medium, or form, in whole or in part, without
# the prior written consent of Tensilica Inc.

EXAMPLE_NAME = hello_world
TARGET_OBJECTS = target/hello.out
NO_TIE = 1

TARGET_SOURCE_PATH = ../../../$(EXAMPLE_NAME)

include ../Makefile.include
include ../Makefile.common


