/* ************************************************************ */
/*Code generated by TC automatically, Please do not modify*/
/*Test : combined*/
/* ************************************************************ */
#ifdef __XTENSA__
#else
#include "cstub-combined.h"
#include <string.h>
#endif
static unsigned databuf[0] = { };

/* ************************************************************ */
void TIE_init_code() {
	/*State initialization*/


	/*Register file  initialization*/

}
